# Authentication settings
auth:
  enabled: true
  rootPassword: changeme
  username: root
  password: changeme
  database: ryze

# Persistent storage settings
persistence:
  enabled: false

# Disable replica set
replicaSet:
  enabled: false
